# Last Insert

np.append(1)

# At specific Position

np.insert(arr, 1,12)

# Delete

np.delete(a, [1])

In [1]:
# Append

import numpy as ns

In [2]:
a = ns.array([1,2,3,4,5])
print(ns.append(a, 6))

[1 2 3 4 5 6]


In [5]:
print(ns.insert(a,5,7))

[1 2 3 4 5 7]


In [ ]:
print(ns.delete(a,1))   # idx [1] ===> 2

[1 3 4 5]


In [ ]:
# 2D

In [ ]:
a = ns.array([[1,2,3,4,5],[6,7,8,9,10]])


[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [8]:
print(ns.append(a,[11,12]))

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [11]:
print(ns.insert(a, 1, [11,12] , axis =1))

[[ 1 11  2  3  4  5]
 [ 6 12  7  8  9 10]]


In [15]:
print("Thank You")

Thank You
