In [1]:
import numpy as ns

In [5]:
arr = ns.array([1,2,3,4,5])
print(arr)

print(ns.sum(arr))

print(ns.min(arr))

print(ns.max(arr))

print(ns.size(arr))

print(ns.mean(arr))

print(ns.cumsum(arr))

print(ns.cumprod(arr))

[1 2 3 4 5]
15
1
5
5
3.0
[ 1  3  6 10 15]
[  1   2   6  24 120]


In [17]:
a = [100,200,300,400,500]
b = [10,20,30,40,50]

print(a+b)

price = ns.array(a)

quantity = ns.array(b)


print(price, "\n", quantity)

print()

print(f"Total Price is: {ns.sum(price)}")
print(f"Total quantity is: {ns.sum(quantity)}")


[100, 200, 300, 400, 500, 10, 20, 30, 40, 50]
[100 200 300 400 500] 
 [10 20 30 40 50]

Total Price is: 1500
Total quantity is: 150


In [18]:
print("Thank You")

Thank You
