In [1]:
import numpy as ns

In [2]:
a = ns.array([1,2,3,4,5])

print(a)

[1 2 3 4 5]


In [3]:
print(type(a))

<class 'numpy.ndarray'>


In [4]:
# Adding multi row in one

a = ns.array([[1,2,3,4,5],[11,22,33,44,55],[111,222,333,444,555]])
print(a)

[[  1   2   3   4   5]
 [ 11  22  33  44  55]
 [111 222 333 444 555]]
