In [ ]:
# Combining and Splitting Arrays

In [2]:
a = [10,20,30]

b = [11,22,33]

print(a+b)

[10, 20, 30, 11, 22, 33]


In [4]:
import numpy as np

In [8]:
arr1 = np.array([1,2,3,4])

arr2 = np.array([1,2,3,4])

print(np.concatenate([arr1, arr2]))

[1 2 3 4 1 2 3 4]


In [9]:
print(np.concatenate([arr1, arr2], axis=0))

[1 2 3 4 1 2 3 4]


In [12]:
arr1 = np.array([1,2,3,4])

arr2 = np.array([1,2,3,4])

print(np.concatenate([arr1, arr2], axis=0))

[1 2 3 4 1 2 3 4]


In [13]:
arr1 = np.array([[1,2,3,4], [1,2,3,4]])

arr2 = np.array([[1,2,3,4], [1,2,3,4]])

print(np.concatenate([arr1, arr2], axis=0))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [ ]:
# Harizontal Stack

print(np.hstack([arr1, arr2])) # Horizontally concat

[[1 2 3 4 1 2 3 4]
 [1 2 3 4 1 2 3 4]]


In [15]:
# Vertical Stack

print(np.vstack([arr1, arr2]))

[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]


In [19]:
a = np.array([1,2,3,4,5,6])

b = np.array_split(a,2)

c = np.array_split(a,6)

print(b)
print()
print(c)

print()

print(b[1])
print()
print(c[1])

[array([1, 2, 3]), array([4, 5, 6])]

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]

[4 5 6]

[2]


In [20]:
print("Thank You")

Thank You
