In [ ]:
# Working with more length of data then needs a NumPy

In [4]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [6]:
import numpy as np

In [7]:
list1 = [1,2,3,4,5]
print(list1)

[1, 2, 3, 4, 5]


In [8]:
list1 = ["Ns Loni", 21, 'Bijapur' , True]
print(list1)

['Ns Loni', 21, 'Bijapur', True]


In [ ]:
# Numpy ---> Numeric Python

# n-d array ---> n-dimentional(1D, 2D, 3D etc.)


In [9]:
numpy_1 = np.array([1,2,3,4,5,6,7,8,9,10])

In [10]:
print(numpy_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [11]:
numpy_1.shape

(10,)

In [12]:
print(type(numpy_1))

<class 'numpy.ndarray'>


In [14]:
numpy_1 = np.arange(10)

In [ ]:
print(numpy_1)

[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Stop where we wanted.....

numpy_1 = np.arange(5)
print(numpy_1)

[0 1 2 3 4]


In [17]:
numpy_1 = np.arange(0,10,2)
print(numpy_1)

[0 2 4 6 8]


In [21]:
numpy_1 = np.zeros(8)
print(numpy_1)

[0. 0. 0. 0. 0. 0. 0. 0.]


In [22]:
# Multi_Dimentional 

numpy_1 = np.zeros((2,10))
print(numpy_1)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


In [24]:
numpy_1 = np.arange((10))
print(numpy_1)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
numpy_1 = np.full((10), 6)
print(numpy_1)

[6 6 6 6 6 6 6 6 6 6]


In [26]:
numpy_1 = np.full((2,10),6)
print(numpy_1)

[[6 6 6 6 6 6 6 6 6 6]
 [6 6 6 6 6 6 6 6 6 6]]


In [ ]:
# Convert from Python list into Numpy

In [27]:
my_list = [1,2,3,4,5,6,7,8,9,10]
numpy_2 = np.array(my_list)
print(numpy_2)

[ 1  2  3  4  5  6  7  8  9 10]


In [28]:
print(numpy_2[4])

5


In [29]:
print('Thank You')

Thank You
