In [ ]:
# c = a-b
# ns.subtract(a,b)
# ns.add
# a/b
# ns.divide(a/b)

# multiply
# exp
# sqrt
# pow
# a*b

In [2]:
import numpy as ns

In [3]:
arr1 = ns.array([[1,2,3],[3,2,1]])
arr2 = ns.array([[1,2,3],[3,2,1]])

print(arr1 + arr2)

[[2 4 6]
 [6 4 2]]


In [4]:
arr1 = ns.array([[1,2,3],[3,2,1]])
arr2 = ns.array([[1,2,3],[3,2,1]])

print(arr1 * arr2)

[[1 4 9]
 [9 4 1]]


In [5]:
arr1 = ns.array([[1,2,3],[3,2,1]])
arr2 = ns.array([[1,2,3],[3,2,1]])

print(arr1 / arr2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [6]:
print(ns.power(arr1, arr2))

[[ 1  4 27]
 [27  4  1]]


In [ ]:
45:00