In [1]:
import numpy as ns 

In [2]:
arr = ns.array([2,1,5,4 ,7,3,6,8,9,10])

print(arr)

[ 2  1  5  4  7  3  6  8  9 10]


In [3]:
# Sort

print(ns.sort(arr))

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
# Search

arr = ns.array([ 1  ,2  ,3  ,4  ,5  ,6  ,7  ,8  ,9 ,10])

print(ns.where(arr == 5))

(array([4], dtype=int64),)


In [12]:
arr = ns.array([ 1  ,2  ,3  ,4  ,5  ,6  ,7  ,8  ,9 ,10])

ss = ns.searchsorted(arr, 5)
print(ss)

4


In [13]:
print("Thank You")

Thank You
