In [1]:
import numpy as ns

In [2]:
a = ns.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [3]:
print(a[0])

1


In [4]:
print(a[:4])

[1 2 3 4]


In [5]:
print(a[3:])

[ 4  5  6  7  8  9 10]


In [7]:
print(a[1:10:2])

[ 2  4  6  8 10]


In [8]:
print(a[::-1])

[10  9  8  7  6  5  4  3  2  1]


In [10]:
b = a.sort()

print(b)

None


In [11]:
print(a[1:2], a[3:5])

[2] [4 5]


In [13]:
print(a[2:4]) 

[3 4]


In [14]:
arr = ns.array([[10,20,30,40,50], [11,22,33,44,55],[66,77,88,99,100]])

print(arr)

[[ 10  20  30  40  50]
 [ 11  22  33  44  55]
 [ 66  77  88  99 100]]


In [15]:
print(ns.shape(arr))

(3, 5)


In [16]:
print(ns.size(arr))

15


In [17]:
print(ns.ndim(arr))

2
