In [1]:
pip install numpy

In [2]:
import numpy as np

In [ ]:
# Slicing

In [3]:
numpy_1 = np.array([1,2,3,4,5,6,7,8,9,10])

print(numpy_1)

[ 1  2  3  4  5  6  7  8  9 10]


In [4]:
print(numpy_1[2])

3


In [5]:
print(numpy_1[2:10])

[ 3  4  5  6  7  8  9 10]


In [8]:
print(numpy_1[-8:-1])

[3 4 5 6 7 8 9]


In [9]:
print(numpy_1[1:10:3])

[2 5 8]


In [10]:
print(numpy_1[::2])

[1 3 5 7 9]


In [11]:
print(numpy_1[::3])

[ 1  4  7 10]


In [12]:
print(numpy_1[::4])

[1 5 9]


In [13]:
print(numpy_1[::5])

[1 6]


In [17]:
numpy_1 = np.array([[1,2,3,4,5,6], [6,7,8,9,10,11]])
print(numpy_1)

[[ 1  2  3  4  5  6]
 [ 6  7  8  9 10 11]]


In [18]:
print(numpy_1[1,3])

9


In [ ]:
print(numpy_1[0:1,      1:3])
#-------------|---------|
#----------->0&1 row, -> in this direction -->

[[2 3]]


In [21]:
print("Thank you")

Thank you
