# NumPy = Numerical Python

# Defines in a Mutli-Dimention and solve more complex problems on maths like liinear algebra, statstics and probalility and more like data science and ai maths.

# it's type of the package.

# Eg: Maths opration to solvee big problem in simple way.

# In python storin ga array take lot time to store all array, but in Numpy it reduce time and space complexity.

# Eg: list_1 = [10,20,30,40]

But in Array --->

# arr = [10 20 30] --> Continueous Memory allocation.

# Store in less memory.

# pip install numpy

# import numpy as np

#  look as following file and folders

In [1]:
import numpy as ns

In [7]:
a = ns.array([10, 20, 30, 40, 50])

b = ns.array([60, 70, 80, 90, 100])

c = ns.array([10, 20, 30, 40, 50])

print(a+c)

print(a)
print(b)
print()
print(a + b)

[ 20  40  60  80 100]
[10 20 30 40 50]
[ 60  70  80  90 100]

[ 70  90 110 130 150]


In [5]:
print(a[1])

20


# Numpy makes to easy to perform a maths oprations.

# Use to create a n-dimentional arrays.

# finding perticular ele is more easy compaire to array.

[List]------------------------------------[Array]
1. List Not handle a Maths Operations.   1. Array handles Maths opeartions.
2. List take more time.                  2. Oppo
3. List is slow compaing to array.       3. Oppo
4. List will store diff data types.      4. Oppo

In [8]:
a = ns.array([1,2,3,4,5,6,7,8,9,10])

print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [9]:
a = ns.array([[1,2,3,4,5,6,7,8,9,10], [11,22,33,44,55,66,77,88,99,111]])

print(a)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  22  33  44  55  66  77  88  99 111]]


In [14]:
a = ns.array([[1,2,3,4,5],[6,7,8,9,10], [11,22,33,44,55],[66,77,88,99,111]])

print(a)

[[  1   2   3   4   5]
 [  6   7   8   9  10]
 [ 11  22  33  44  55]
 [ 66  77  88  99 111]]


In [16]:
print("Thanks NS-LONI")

Thanks NS-LONI
